import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/lib/providers";

import PageLayout from "./components/PageLayout";

import "./globals.css";
import "./page.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Dynamic App",
  description: "Generated by create dynamic app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <PageLayout>{children}</PageLayout>
        </Providers>
      </body>
    </html>
  );
}
